export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const INCREASE_VALUE='INCREASE_VALUE';
export const SET_USER='SET_USER';
export const ADD_TO_CART='ADD_TO_CART';
export const REMOVE_FROM_CART='REMOVE_FROM_CART';
export const SET_SEARCH_KEYWORD='SET_SEARCH_KEYWORD';
export const RESET_CART='RESET_CART';





