import Home from '../views/customer/Home';
import Order from '../views/customer/Order';
import Categories from '../views/customer/Categories';
import Community from '../views/customer/Community';
import Feed from '../views/customer/Feed';
import Restaurants from '../views/customer/Restaurants';
import RestaurantHome from '../views/restaurant/RestaurantHome';
import RestaurantProducts from '../views/restaurant/RestaurantProducts';
import OrdersView from '../views/restaurant/OrdersView';
import Reservation from '../views/restaurant/Reservation';
import Shopping from '../views/restaurant/Shopping';
import RestaurantProductAdd from '../views/restaurant/RestaurantProductAdd';
import AdminHome from '../views/admin/AdminHome';
import Staff from '../views/admin/Staff';
import Analytics from '../views/admin/Analytics';
import Riders from '../views/admin/Riders';
import Profile from '../views/common/Profile';
import StaffHome from '../views/staff/StaffHome';
import Payments from '../views/staff/Payments';
import Complains from '../views/staff/Complains';
import Sales from '../views/admin/Sales';
import ManufactureHome from '../views/manufacture/ManufactureHome'
import RowProducts from '../views/manufacture/RowProducts'
import RowOrderView from '../views/manufacture/RowOrderView'
import ManufactureComplains from '../views/manufacture/ManufactureComplains'
export {Sales, StaffHome, Payments, Complains, AdminHome, Staff, Analytics, Riders, Profile, Home, Order, Categories, Community, Feed, Restaurants, RestaurantHome, RestaurantProducts, OrdersView, Shopping, Reservation, RestaurantProductAdd, ManufactureHome,RowProducts,RowOrderView,ManufactureComplains};
