import Home from "../views/customer/Home";
import Order from "../views/customer/Order";
import Categories from "../views/customer/Categories";
import Community from "../views/customer/Community";
import Feed from "../views/customer/Feed";
import Restaurants from "../views/customer/Restaurants";
import RestaurantHome from "../views/restaurant/RestaurantHome";
import RestaurantProducts from "../views/restaurant/RestaurantProducts";
import OrdersView from "../views/restaurant/OrdersView";
import Reservation from "../views/restaurant/Reservation";
import Shopping from "../views/restaurant/Shopping";
import RestaurantProductAdd from "../views/restaurant/RestaurantProductAdd";
export { Home, Order, Categories, Community, Feed, Restaurants, RestaurantHome, RestaurantProducts, OrdersView, Shopping, Reservation, RestaurantProductAdd };
