import Home from '../views/customer/Home';
import Order from '../views/customer/Order';
import Categories from '../views/customer/Categories';
import Community from '../views/customer/Community';
import Feed from '../views/customer/Feed';
import Restaurants from '../views/customer/Restaurants';
import RestaurantHome from '../views/restaurant/RestaurantHome';
import RestaurantProducts from '../views/restaurant/RestaurantProducts';
import OrdersView from '../views/restaurant/OrdersView';
import Reservation from '../views/restaurant/Reservation';
import Shopping from '../views/restaurant/Shopping';
import RestaurantProductAdd from '../views/restaurant/RestaurantProductAdd';
import RestaurantComplain from '../views/restaurant/RestaurantComplain';
import AdminHome from '../views/admin/AdminHome';
import Staff from '../views/admin/Staff';
import Analytics from '../views/admin/Analytics';
import Cart from '../views/customer/Cart';
import Riders from '../views/admin/Riders';
import Profile from '../views/common/Profile';
import About from '../views/customer/About';
import StaffHome from '../views/staff/StaffHome';
import Payments from '../views/staff/Payments';
import Complaints from '../views/staff/Complaints';
import Users from '../views/staff/Users';
import Sales from '../views/admin/Sales';
import ManufactureHome from '../views/manufacture/ManufactureHome'
import RowProducts from '../views/manufacture/RowProducts'
import RowOrderView from '../views/manufacture/RowOrderView'
import ManufactureComplains from '../views/manufacture/ManufactureComplains'
import View_Profile from '../views/customer/view_profile';
import Recipe from '../views/customer/Recipe';
import SelectedRestaurant from '../views/customer/SelectedRestaurant';
import recipeForm from '../views/customer/recipeForm';
import location from '../views/customer/location';
import communityOrganizerForm from '../views/customer/CommunityOrganizerForm';
import SearchResults from '../views/customer/SearchResults';
import AdminProfile from '../views/admin/AdminProfile';
export {Sales, StaffHome, Payments, Complains, AdminHome, Staff, Analytics, Riders, Profile, Home, Order, Categories, Community, Feed, Restaurants, RestaurantHome, RestaurantProducts, OrdersView, Shopping, Reservation, RestaurantProductAdd,Cart, ManufactureHome,RowProducts,RowOrderView,ManufactureComplains,RestaurantComplain,About,View_Profile,SelectedRestaurant,Recipe,recipeForm,location,communityOrganizerForm,SearchResults,AdminProfile};
